version: '3.8'

services:
  web:
    build: ../
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    environment:
      - FLASK_ENV=production
      - JWT_SECRET_KEY=your_jwt_secret_key
      - LOGGING_LEVEL=INFO
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db