version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  web:
    build: ../
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    depends_on:
      - redis
  
volumes:
  redis-data: