k8s_yaml('k8s/deployment.yaml')
k8s_resource('finmind-web', port_forwards=5000)

docker_build('finmind-web', './app')

local_resource(
    'db',
    'docker run -d --name finmind-db -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=finmind postgres:13',
    resource_deps=['finmind-web'],
    restart_on=['./backend/app/db/schema.sql']
)

local_resource(
    'redis',
    'docker run -d --name finmind-redis redis:6',
    resource_deps=['finmind-web'],
)

allow_k8s_contexts('docker-desktop')

watch_settings(
    watch_file_changes=True,
    watch_dirs=['./app'],
)

update_settings(
    delete_unused=True,
)