k8s_yaml('k8s/*.yaml')

docker_build('finmind-backend', './app')

k8s_resource('finmind-backend', port_forwards=5000)

k8s_resource('finmind-db', port_forwards=5432)

k8s_resource('finmind-redis', port_forwards=6379)

local_resource(
    'apply-migrations',
    cmd='docker-compose run web flask db upgrade',
    deps=['./app/migrations'],
    resource_deps=['finmind-db'],
)

local_resource(
    'seed-db',
    cmd='docker-compose run web flask seed',
    resource_deps=['apply-migrations'],
)

local_resource(
    'run-tests',
    cmd='docker-compose run web pytest',
    resource_deps=['apply-migrations'],
)