k8s_yaml('k8s/*.yaml')

docker_build('finmind-backend', './app')

k8s_resource('finmind-backend', port_forwards=8000)

local_resource(
    'db',
    'docker run -d --name finmind-db -e POSTGRES_USER=finmind -e POSTGRES_PASSWORD=finmind -e POSTGRES_DB=finmind postgres:13',
    resource_deps=['finmind-backend'],
    restart_on=['k8s/*.yaml'],
    port_forwards=5432
)

local_resource(
    'redis',
    'docker run -d --name finmind-redis redis:6',
    resource_deps=['finmind-backend'],
    restart_on=['k8s/*.yaml'],
    port_forwards=6379
)

watch_settings(
    watch_dirs=['app'],
    ignore=['*.pyc', '__pycache__'],
)